- name: Install Java
  hosts: testservers
  become: yes
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      yum:
        update_cache: yes
    - name: Install Java using Ansible
      become_user: root
      become_method: sudo
      yum:
        name: "{{ packages }}"
      vars:
        packages:
           - java-1.8.0-openjdk
           
    - name: Setting default java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/jre-1.8.0-openjdk*
